<?php
/**
 * Functions that define and add breadcrumb markup to pages
 */
namespace FinAid\Theme\Includes\Breadcrumb;


/**
 * Returns the desired top-level wrapper element
 * for breadcrumbs generated by Yoast.
 *
 * @since 1.0.0
 * @author Jo Dickson
 * @param string $element HTML element name
 * @return string HTML element name
 */
function breadcrumb_output_wrapper( $element ) {
	return 'ol';
}

add_filter( 'wpseo_breadcrumb_output_wrapper', __NAMESPACE__ . '\breadcrumb_output_wrapper' );


/**
 * Returns the desired HTML classes to apply to the top-level
 * wrapper element for breadcrumbs generated by Yoast.
 *
 * @since 1.0.0
 * @author Jo Dickson
 * @param string $element HTML class name
 * @return string HTML class name
 */
function breadcrumb_output_class( $class ) {
	return 'breadcrumb mb-0';
}

add_filter( 'wpseo_breadcrumb_output_class', __NAMESPACE__ . '\breadcrumb_output_class' );


/**
 * Returns the desired wrapper element for individual links
 * in breadcrumbs generated by Yoast.
 *
 * @since 1.0.0
 * @author Jo Dickson
 * @param string $element HTML element name
 * @return string HTML element name
 */
function breadcrumb_single_link_wrapper( $element ) {
	return 'li';
}

add_filter( 'wpseo_breadcrumb_single_link_wrapper', __NAMESPACE__ . '\breadcrumb_single_link_wrapper' );


/**
 * Returns the desired breadcrumb separator in breadcrumbs
 * generated by Yoast.
 *
 * @since 1.0.0
 * @author Jo Dickson
 * @param string $separator Provided separator value
 * @return string Modified separator value
 */
function breadcrumb_separator( $separator ) {
	return '';
}

add_filter( 'wpseo_breadcrumb_separator', __NAMESPACE__ . '\breadcrumb_separator' );


/**
 * Modifies generated markup for a single list item in a Yoast breadcrumb.
 *
 * @since 1.0.0
 * @author Jo Dickson
 * @param string $html Generated list item HTML
 * @param array $link Single link data
 * @return string Modified list item HTML
 */
function breadcrumb_single_link( $html, $link ) {
	// Add breadcrumb-item class to individual list items
	$html = str_replace( '<li>', '<li class="breadcrumb-item">', $html );
	// Disable <strong> tag usage around last breadcrumb item
	$html = str_replace( '<strong', '<li', $html );
	$html = str_replace( '</strong>', '</li>', $html );

	return $html;
}

add_filter( 'wpseo_breadcrumb_single_link', __NAMESPACE__ . '\breadcrumb_single_link', 10, 2 );


/**
 * Modifies generated markup for breadcrumbs generated by Yoast.
 *
 * @since 1.0.0
 * @author Jo Dickson
 * @param string $html Generated breadcrumb HTML
 * @return string Modified breadcrumb HTML
 */
function breadcrumb_output( $output ) {
	// Replace the 'last' class provided by Yoast with Athena classes
	$output = str_replace( 'breadcrumb_last', 'breadcrumb-item active', $output );
	return $output;
}

add_filter( 'wpseo_breadcrumb_output', __NAMESPACE__ . '\breadcrumb_output' );


/**
 * Returns breadcrumb markup if Yoast breadcrumb logic is available.
 *
 * @since 1.0.0
 * @author Jo Dickson
 * @return string HTML markup for the breadcrumbs and wrapper container
 */
function get_breadcrumb_markup() {
	$markup = '';

	if ( ! is_home() && ! is_front_page() ) {
		if ( function_exists( 'yoast_breadcrumb' ) ) {
			ob_start();
		?>
		<nav class="site-breadcrumb bg-faded mb-0 py-3" aria-label="Breadcrumb">
			<div class="container">
				<?php echo yoast_breadcrumb( '', '', false ); ?>
			</div>
		</nav>
		<?php
			$markup = trim( ob_get_clean() );
		}
	}

	return $markup;
}


/**
 * Filters editable Yoast breadcrumb options
 *
 * @since 1.0.0
 * @author Jo Dickson
 * @param array $options Array of `wpseo_titles` options + values
 * @return array Modified array of options + values
 */
function filter_yoast_options_breadcrumbs( $options ) {
	// Force breadcrumb separator value to always be empty
	$options['breadcrumbs-sep'] = '';
	// Force bolding on last breadcrumb items (consistent with Athena Framework
	// styling; generated markup is modified in `breadcrumb_single_link`)
	$options['breadcrumbs-boldlast'] = 'on';

	return $options;
}

add_filter( 'option_wpseo_titles', __NAMESPACE__ . '\filter_yoast_options_breadcrumbs');
